
name: augmented-maskrcnn
#prefix: /your/custom/path/envs/augmented-maskrcnn
channels:
  - conda-forge
  - pytorch
  - anaconda
dependencies:
  - python=3.6
  - pip
  - anaconda::cython 
  - pytorch::torchvision>=0.5.0
  - pytorch::pytorch>=1.0.1
  - anaconda::cudatoolkit=10.1
  - anaconda::jsonschema>=2.6.0
  - albumentations::albumentations=0.4.5
  - numpy=1.17
  - pip:
    - opencv-python
    - git+https://github.com/gautamchitnis/cocoapi.git#subdirectory=PythonAPI